import { APP_VERSION, ENABLE_SW } from './config.v48.js';
import { saveSession, readSession, clearSession } from './auth.v48.js';
import { state, resetPath, softBackAfterSave } from './state.v48.js';
import { collapseCatalog, getNodeAtPath } from './catalog.v48.js';
import { collectRecords } from './inventory.v48.js';
import { adminRebuild, adminWarm, getCatalog, getCurrentStock, getOrderView, health, submitRecords } from './api.v48.js';
import { dom, renderAdmin, renderBreadcrumbs, renderItems, renderNavCards, renderRootHint, setAuthUi, setHealth, setLoadingContent, setModeUi, setSaveLock, toast } from './ui.v48.js';
import { debounce, getQueryFlag, qsa } from './utils.v48.js';
const ACTION_BY_MODE={count:'count',issue:'issue',receive:'receive',order:'order'};
const adminMode=getQueryFlag('admin');
function bindOnce(){const el=dom();el.loginBtn.addEventListener('click',handleLogin);el.logoutBtn.addEventListener('click',handleLogout);el.employeeInput.addEventListener('keydown',e=>{if(e.key==='Enter')handleLogin();});qsa('[data-mode]',el.modeGrid).forEach(btn=>btn.addEventListener('click',()=>selectMode(btn.dataset.mode)));el.homeBtn.addEventListener('click',()=>{resetPath();render();});el.backBtn.addEventListener('click',()=>{state.path.pop();render();});el.refreshBtn.addEventListener('click',async()=>{try{await refreshModeData(true);toast('รีเฟรชแล้ว','success');render();}catch(e){toast(e.message||'รีเฟรชไม่สำเร็จ','error');}});el.clearBtn.addEventListener('click',()=>{state.pendingValues={};render();});el.saveBtn.addEventListener('click',handleSave);el.rebuildBtn?.addEventListener('click',async()=>{const res=await adminRebuild();toast(res?.ok?'Rebuild เสร็จแล้ว':'Rebuild ไม่สำเร็จ',res?.ok?'success':'error');});el.warmBtn?.addEventListener('click',async()=>{const res=await adminWarm();toast(res?.ok?'Warm cache เสร็จแล้ว':'Warm cache ไม่สำเร็จ',res?.ok?'success':'error');});dom().content.addEventListener('click',onContentClick);dom().content.addEventListener('input',debounce(onContentInput,60));}
function sessionPayload(){return {employee:state.employee,version:APP_VERSION};}
function handleLogin(){const name=dom().employeeInput.value.trim();if(!name)return toast('กรุณากรอกชื่อพนักงาน','warn');state.employee=name;saveSession(sessionPayload());setAuthUi(true);toast('เข้าสู่ระบบแล้ว','success');}
function handleLogout(){clearSession();state.employee='';state.mode='';resetPath();state.pendingValues={};dom().employeeInput.value='';setAuthUi(false);setModeUi('');render();toast('ออกจากระบบแล้ว','info');}
async function checkHealth(){try{const res=await health();setHealth(!!res?.ok,res?.ok?`พร้อมใช้งาน • ${res.version||APP_VERSION}`:'health check ไม่ผ่าน');}catch{setHealth(false,'เชื่อมต่อ backend ไม่ได้');}}
async function bootstrap(){renderAdmin(adminMode);bindOnce();const session=readSession();if(session?.employee){state.employee=session.employee;dom().employeeInput.value=session.employee;setAuthUi(true);}render();await checkHealth();if(ENABLE_SW&&'serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
async function loadCatalog(mode){const res=await getCatalog(mode);if(!res?.ok)throw new Error(res?.message||'โหลด catalog ไม่สำเร็จ');state.catalogs[mode]=collapseCatalog(res.rows||res.catalog_rows||[]);}
async function refreshModeData(force=false){if(!state.mode)return;if(!state.catalogs[state.mode]||force)await loadCatalog(state.mode);if(state.mode==='order'){const order=await getOrderView();state.orderMap=Object.fromEntries((order.rows||[]).map(r=>[r.item_key,r]));const stock=await getCurrentStock();state.stockMap=Object.fromEntries((stock.rows||[]).map(r=>[r.item_key,r]));}else{const stock=await getCurrentStock();state.stockMap=Object.fromEntries((stock.rows||[]).map(r=>[r.item_key,r]));}}
async function selectMode(mode){if(!state.employee)return toast('กรุณาเข้าสู่ระบบก่อน','warn');state.mode=mode;state.pendingValues={};resetPath();setModeUi(mode);setLoadingContent();try{await refreshModeData(false);render();}catch(e){toast(e.message||'โหลดข้อมูลไม่สำเร็จ','error');render();}}
function currentNode(){return getNodeAtPath(state.catalogs[state.mode]||{},state.path);}
function currentItems(){return currentNode().items||[];}
function render(){if(!state.mode){renderRootHint();dom().toolbar.classList.add('hidden');return;}dom().toolbar.classList.remove('hidden');renderBreadcrumbs();const node=currentNode();if(state.path.length===0){renderNavCards(Object.values(state.catalogs[state.mode]||{}),'top');return;}if(state.path.length===1){renderNavCards(Object.values(node.children||{}),'main');return;}if(state.path.length===2){renderNavCards(Object.values(node.children||{}),'sub');return;}renderItems(currentItems());}
function onContentClick(e){const navBtn=e.target.closest('[data-nav-level]');if(navBtn){state.path.push(navBtn.dataset.key);render();return;}const plusBtn=e.target.closest('[data-plus]');if(plusBtn){const key=plusBtn.dataset.target;const amount=Number(plusBtn.dataset.plus||0);state.pendingValues[key]=Number(state.pendingValues[key]||0)+amount;const input=dom().content.querySelector(`[data-qty="${key}"]`);if(input)input.value=state.pendingValues[key];return;}const suggestBtn=e.target.closest('[data-suggest]');if(suggestBtn){const key=suggestBtn.dataset.suggest;const suggested=Number(state.orderMap[key]?.suggested_order_qty||0);state.pendingValues[key]=suggested;const input=dom().content.querySelector(`[data-qty="${key}"]`);if(input)input.value=suggested;}}
function onContentInput(e){const input=e.target.closest('[data-qty]');if(!input)return;state.pendingValues[input.dataset.qty]=input.value;}
async function handleSave(){if(state.saveLock)return;const items=currentItems();const records=collectRecords(items);if(!records.length)return toast('ยังไม่มีรายการให้บันทึก','warn');setSaveLock(true);toast('Saving...','info',1400);try{const res=await submitRecords(ACTION_BY_MODE[state.mode],records);if(!res?.ok&&!res?.duplicate)throw new Error(res?.message||'save fail');await refreshModeData(true);state.pendingValues={};softBackAfterSave();render();toast(res?.duplicate?'Duplicate request ถูกกันไว้แล้ว':'Saved','success');}catch(e){toast(e.message||'Error','error',3500);}finally{setSaveLock(false);}}
bootstrap();
