import { ENABLE_SERVICE_WORKER } from "./config.v51.js";
import { state, setEmployee, setMode, resetNav } from "./state.v51.js";
import { restoreSession, persistSession, logoutSession } from "./auth.v51.js";
import { bindDom, renderSession, setHealth, showError, toast, renderAdmin, renderBreadcrumb, renderDestinationPicker, renderNodesFromHtml, renderItems, renderSkeleton, setSaveLocked, renderInfoBanner } from "./ui.v51.js";
import { getCatalog, getCurrentStock, getOrderView, health, submitAction, clearDataCaches, adminWarm, adminNightly, diagnostics, preflight } from "./api.v51.js";
import { getNodeByPath, needsDestination, warmCatalogMode, getWarmMode } from "./catalog.v51.js";
import { collectRows } from "./inventory.v51.js";
import { $, $$, createRequestId, params, debounce } from "./utils.v51.js";
import { setDraft, getDraft, clearDraft } from "./store.v51.js";
let prewarmPromise = null;
function currentWarm() { return getWarmMode(state.mode); }
function currentTree() { return currentWarm().tree; }
function currentNode() { return getNodeByPath(currentTree(), state.path) || currentTree(); }
function currentHtml() { return currentWarm().html; }
function readInputValues() { return $$('[data-qty-index]', document).map((el) => ({ index: Number(el.dataset.qtyIndex), value: el.value.trim() })); }
const autosaveDraft = debounce(() => { const values = readInputValues().filter((x) => x.value !== ""); if (!values.length || !state.mode || !state.employee) return; setDraft({ employee: state.employee, mode: state.mode, path: [...state.path], destination: state.destination, values }); }, 250);
function attachInputAutosave() { $$('[data-qty-index]', document).forEach((el) => el.addEventListener('input', autosaveDraft)); $('clearBtn')?.addEventListener('click', () => { $$('[data-qty-index]', document).forEach((el) => el.value = ''); clearDraft(); toast('ล้างค่าแล้ว'); }); $('restoreBtn')?.addEventListener('click', () => { const draft = getDraft()?.value; if (!draft || draft.mode !== state.mode) return toast('ไม่พบข้อมูลค้าง', 'info'); draft.values.forEach((row) => { const input = document.querySelector(`[data-qty-index="${row.index}"]`); if (input) input.value = row.value; }); toast('กู้ข้อมูลค้างแล้ว', 'success'); }); }
async function refreshHealth() { try { const res = await health(); state.nightlyCutoffHour = Number(res?.nightlyCutoffHour || 22); setHealth(!!res?.ok, res?.ok ? `พร้อมใช้งาน • คำนวณรอบ ${state.nightlyCutoffHour}:00` : `มีปัญหา • ${res?.message || ''}`); } catch (err) { setHealth(false, 'เชื่อมต่อไม่สำเร็จ'); } }
async function refreshDiagnostics() { if (!state.admin) return; try { const [diag, pf] = await Promise.all([diagnostics().catch(() => null), preflight().catch(() => null)]); const lines = []; if (diag?.ok) lines.push(`nightly runs: ${diag.diagnostics.nightlyRuns || 0} • last nightly: ${diag.diagnostics.lastNightlyAt || '-'}`); if (pf?.ok) lines.push(`preflight: ${pf.summary.status}`); state.infoBanner = lines.join(' | ') || 'Count/Issue/Receive/Order = append log only'; renderAdmin(); } catch (err) {} }
function applyWarmMode(mode, rows, cached = false) { const warmed = warmCatalogMode(mode, rows || []); state.catalogRowsByMode[mode] = rows || []; state.treeByMode[mode] = warmed.tree; state.instantReadyModes[mode] = true; if (state.mode === mode) { state.scheduleBadgeByPath = warmed.scheduleBadgeByPath; state.lastCacheStamp = cached ? 'ใช้ cache • snapshot ล่าสุดจากรอบ 22:00' : 'โหลดสด • snapshot ล่าสุดจากรอบ 22:00'; } }
async function ensureCatalogLoaded(mode, force = false) { if (!force && state.instantReadyModes[mode]) return; if (state.loadingModes[mode]) return state.loadingModes[mode]; state.loadingModes[mode] = (async () => { const catalog = await getCatalog(mode); if (!catalog?.ok) throw new Error(catalog?.message || 'โหลด catalog ไม่สำเร็จ'); applyWarmMode(mode, catalog.rows || [], !!catalog.cached); })(); try { await state.loadingModes[mode]; } finally { delete state.loadingModes[mode]; } }
async function ensureSideData(mode) { if (mode === 'order') { const orderRes = await getOrderView(); if (!orderRes?.ok) throw new Error(orderRes?.message || 'โหลด order view ไม่สำเร็จ'); state.orderRows = orderRes.rows || []; } else { const stockRes = await getCurrentStock(); if (!stockRes?.ok) throw new Error(stockRes?.message || 'โหลด stock ไม่สำเร็จ'); state.stockMap = stockRes.stock || {}; } }
async function prewarmOtherModes(activeMode) { if (prewarmPromise) return prewarmPromise; const otherModes = ['count','issue','receive','order'].filter((m) => m !== activeMode); prewarmPromise = (async () => { for (const mode of otherModes) { try { await ensureCatalogLoaded(mode); } catch (err) {} } })(); try { await prewarmPromise; } finally { prewarmPromise = null; } }
function render() { renderSession(); renderAdmin(); renderDestinationPicker(); renderInfoBanner(); if (!state.employee || !state.mode) return; renderBreadcrumb(currentTree()); const node = currentNode(); const html = currentHtml(); if (state.path.length === 0 && html.targets) { renderNodesFromHtml(html.targets, (key) => { state.path.push(key); showError(''); render(); }); return; } if (state.path.length === 1 && html.subsByTarget?.[state.path[0]]) { renderNodesFromHtml(html.subsByTarget[state.path[0]], (key) => { state.path.push(key); showError(''); render(); }); return; } const children = Object.keys(node?.children || {}); if (children.length) { renderNodesFromHtml('', () => {}); return; } renderItems(node, state.stockMap, state.orderRows, handleSave); attachInputAutosave(); setSaveLocked(state.saveInFlight); }
async function chooseMode(mode) { setMode(mode); showError(''); render(); renderSkeleton(); await ensureCatalogLoaded(mode); state.scheduleBadgeByPath = getWarmMode(mode).scheduleBadgeByPath; await ensureSideData(mode); render(); prewarmOtherModes(mode); }
async function handleSave() { if (state.saveInFlight) return; try { showError(''); const node = currentNode(); if (needsDestination(state.mode) && !state.destination) throw new Error('กรุณาเลือกปลายทางการเบิก'); const rows = collectRows(node, readInputValues()); const requestId = createRequestId(); state.saveInFlight = true; setSaveLocked(true, 'Saving...'); toast('รับรายการแล้ว • ยังไม่คำนวณทันที', 'info', 1200); const res = await submitAction(state.mode, requestId, rows); if (!res?.ok) throw new Error(res?.message || 'บันทึกไม่สำเร็จ'); clearDraft(); if (state.path.length) state.path.pop(); render(); toast(`Accepted • คำนวณรอบ ${state.nightlyCutoffHour}:00`, 'success', 2200); } catch (err) { showError(err?.message || 'บันทึกไม่สำเร็จ'); toast('Error', 'error'); } finally { state.saveInFlight = false; setSaveLocked(false); } }
function bindEvents() { $('loginBtn').addEventListener('click', () => { const name = $('employeeName').value.trim(); if (!name) return showError('กรุณากรอกชื่อพนักงาน'); try { setEmployee(name); persistSession(name); showError(''); render(); } catch (err) { console.error(err); showError('เข้าสู่ระบบไม่สำเร็จ'); } }); $('employeeName').addEventListener('keydown', (e) => { if (e.key === 'Enter') $('loginBtn').click(); }); $('logoutBtn').addEventListener('click', () => { logoutSession(); resetNav(); state.mode = ''; render(); }); $$('[data-mode]').forEach((el) => el.addEventListener('click', () => chooseMode(el.dataset.mode))); $('homeBtn').addEventListener('click', () => { resetNav(); render(); }); $('backBtn').addEventListener('click', () => { state.path.pop(); render(); }); $('destinationButtons').addEventListener('click', (e) => { const btn = e.target.closest('[data-dest]'); if (!btn) return; state.destination = btn.dataset.dest; renderDestinationPicker(); }); $('warmBtn')?.addEventListener('click', async () => { const res = await adminWarm(); toast(res?.ok ? 'Warm cache สำเร็จ' : 'Warm cache ไม่สำเร็จ', res?.ok ? 'success' : 'error'); refreshDiagnostics(); }); $('nightlyBtn')?.addEventListener('click', async () => { const res = await adminNightly(); toast(res?.ok ? `Nightly สำเร็จ • ${res.orderRows} รายการตก` : 'Nightly ไม่สำเร็จ', res?.ok ? 'success' : 'error', 2500); if (res?.ok) { clearDataCaches(); await ensureSideData(state.mode || 'count'); render(); } refreshDiagnostics(); }); $('preflightBtn')?.addEventListener('click', async () => { const pf = await preflight(); toast(pf?.ok ? `Preflight ${pf.summary.status}` : 'Preflight ไม่สำเร็จ', pf?.ok ? 'success' : 'error', 2500); state.infoBanner = pf?.ok ? `preflight: ${pf.summary.status}` : 'preflight failed'; renderAdmin(); }); }
async function bootstrap() { bindDom(); state.admin = params().get('admin') === '1'; restoreSession(); bindEvents(); render(); await refreshHealth(); await refreshDiagnostics(); if (ENABLE_SERVICE_WORKER && 'serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {}); }
bootstrap();
