import { MODES } from './config.v48.js';
import { formatNumber, qs } from './utils.v48.js';
import { state } from './state.v48.js';
const el={app:qs('#app'),healthText:qs('#healthText'),employeeInput:qs('#employeeInput'),loginBtn:qs('#loginBtn'),logoutBtn:qs('#logoutBtn'),modeGrid:qs('#modeGrid'),toolbar:qs('#toolbar'),breadcrumbs:qs('#breadcrumbs'),content:qs('#content'),footerBar:qs('#footerBar'),footerHint:qs('#footerHint'),saveBtn:qs('#saveBtn'),clearBtn:qs('#clearBtn'),homeBtn:qs('#homeBtn'),backBtn:qs('#backBtn'),refreshBtn:qs('#refreshBtn'),toastWrap:qs('#toastWrap'),adminPanel:qs('#adminPanel'),rebuildBtn:qs('#rebuildBtn'),warmBtn:qs('#warmBtn')};
export const dom=()=>el;
export function setHealth(ok,text){el.healthText.textContent=text||(ok?'พร้อมใช้งาน':'ระบบมีปัญหา');}
export function toast(message,type='info',ms=2200){const node=document.createElement('div');node.className=`toast ${type}`;node.textContent=message;el.toastWrap.appendChild(node);setTimeout(()=>node.remove(),ms);}
export function setAuthUi(loggedIn){el.loginBtn.classList.toggle('hidden',loggedIn);el.logoutBtn.classList.toggle('hidden',!loggedIn);el.employeeInput.disabled=loggedIn;}
export function setModeUi(mode){[...el.modeGrid.querySelectorAll('[data-mode]')].forEach(btn=>btn.classList.toggle('active',btn.dataset.mode===mode));}
export function setLoadingContent(){el.toolbar.classList.toggle('hidden',!state.mode);el.content.innerHTML='<div class="grid"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>';}
export function setSaveLock(locked){state.saveLock=locked;el.saveBtn.disabled=locked;el.footerHint.textContent=locked?'กำลังบันทึก...':'พร้อมบันทึก';}
export function renderBreadcrumbs(){const labels=[MODES[state.mode]?.label||''];const tree=state.catalogs[state.mode]||{};if(state.path[0])labels.push(tree[state.path[0]]?.label||state.path[0]);if(state.path[1])labels.push(tree[state.path[0]]?.children?.[state.path[1]]?.label||state.path[1]);if(state.path[2])labels.push(tree[state.path[0]]?.children?.[state.path[1]]?.children?.[state.path[2]]?.label||state.path[2]);el.breadcrumbs.innerHTML=labels.filter(Boolean).map(x=>`<span class="chip">${x}</span>`).join('');}
function stockMeta(item){const stock=state.stockMap[item.item_key];const order=state.orderMap[item.item_key];const parts=[`หน่วย ${item.unit||'-'}`];if(stock)parts.push(`คงเหลือ ${formatNumber(stock.current_stock)}`);if(order?.suggested_order_qty>0&&state.mode==='order')parts.push(`แนะนำ ${formatNumber(order.suggested_order_qty)}`);return parts.map(x=>`<span class="pill">${x}</span>`).join('');}
export function renderNavCards(nodes,level){el.content.innerHTML=`<div class="grid">${nodes.map(n=>`<button class="card nav-card" data-nav-level="${level}" data-key="${n.key}"><strong>${n.label}</strong><div class="muted">เลือก${level==='top'?'หมวดหลัก':level==='main'?'หมวดย่อย':'รายการ'}</div></button>`).join('')}</div>`;el.footerBar.classList.add('hidden');}
export function renderItems(items){el.content.innerHTML=`<section class="card section"><h3>รายการทั้งหมด ${items.length} รายการ</h3><div class="list">${items.map(item=>`<div class="item" data-item="${item.item_key}"><div class="item-top"><div><strong>${item.item_name}</strong><div class="meta">${stockMeta(item)}</div></div>${state.mode==='order'?`<button class="btn secondary" data-suggest="${item.item_key}">แนะนำ</button>`:''}</div><div class="qty"><input type="number" min="0" step="1" placeholder="จำนวน" value="${state.pendingValues[item.item_key]??''}" data-qty="${item.item_key}" /><div class="quick"><button type="button" data-plus="1" data-target="${item.item_key}">+1</button><button type="button" data-plus="5" data-target="${item.item_key}">+5</button><button type="button" data-plus="10" data-target="${item.item_key}">+10</button></div></div></div>`).join('')}</div></section>`;el.footerBar.classList.remove('hidden');}
export function renderRootHint(){el.content.innerHTML='<section class="card section"><h3>เริ่มต้นใช้งาน</h3><div class="muted">กรุณาเข้าสู่ระบบ แล้วเลือกโหมดการทำงาน</div></section>';el.footerBar.classList.add('hidden');}
export function renderAdmin(show){el.adminPanel.classList.toggle('hidden',!show);}
